site_name: PiXe1ERan9E's Notebook
theme:
  name: material
  nav_style: light
  custom_dir: docs/resources/
  highlightjs: true
  hljs_languages:
    - yaml
use_directory_urls: false
markdown_extensions:
  - pymdownx.arithmatex:
    generic: true
